CREATE TABLE `test123` (
  `Id` char(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `Message` longtext,
  `Direction` tinyint(1) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TRIGGER `Test123_IdentityTgr` BEFORE INSERT ON `test123` FOR EACH ROW BEGIN
SET NEW.Id = UUID();
DROP TEMPORARY TABLE IF EXISTS tmpIdentity_Test123;
CREATE TEMPORARY TABLE tmpIdentity_Test123 (guid CHAR(36))ENGINE=MEMORY;
INSERT INTO tmpIdentity_Test123 VALUES(New.Id);
END;